import ffmpeg from 'fluent-ffmpeg'
import ffmpegInstaller from '@ffmpeg-installer/ffmpeg'
import ffprobeInstaller from '@ffprobe-installer/ffprobe'
import path from 'path'
import fs from 'fs'
import sharp from 'sharp'

ffmpeg.setFfmpegPath(ffmpegInstaller.path)
ffmpeg.setFfprobePath(ffprobeInstaller.path)
export function sampleFrames(inputPath, framesDir) {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(framesDir)) fs.mkdirSync(framesDir, { recursive: true })
    ffmpeg(inputPath)
      .output(path.join(framesDir, 'frame-%03d.png'))
      .outputOptions(['-vf fps=10,scale=960:-1', '-f image2'])
      .on('end', resolve)
      .on('error', reject)
      .run()
  })
}

export async function buildSummaryPoster({ analysis, compare, outPath }) {
  const w = 1280
  const h = 720
  const bg = { r: 10, g: 14, b: 18, alpha: 1 }
  const text = [
    { t: 'Shot Speed', v: `${Math.round(analysis.speed_mps)} m/s (${Math.round(analysis.speed_kmh)} km/h)` },
    { t: 'Contact Force', v: `${Math.round(analysis.contact_force_N)} N` },
    { t: 'Posture Score', v: `${Math.round(analysis.posture_score)}/100` },
    { t: 'Posture Notes', v: analysis.posture_notes || '' }
  ]
  const compareText = [
    { t: 'Percent of speed of sound', v: `${Math.round(analysis.speed_mps / compare.sound_mps * 100)}%` },
    { t: 'Percent of bullet muzzle velocity', v: `${Math.round(analysis.speed_mps / compare.bullet_mps * 100)}%` },
    { t: 'Percent of cheetah top speed', v: `${Math.round(analysis.speed_mps / compare.cheetah_mps * 100)}%` }
  ]
  const svg = `
    <svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="${w}" height="${h}" fill="rgb(${bg.r},${bg.g},${bg.b})"/>
      <text x="50" y="80" fill="#00e676" font-family="Arial" font-size="48" font-weight="bold">Football Shot Analysis</text>
      <text x="50" y="150" fill="#ffffff" font-family="Arial" font-size="28">${text[0].t}: ${text[0].v}</text>
      <text x="50" y="200" fill="#ffffff" font-family="Arial" font-size="28">${text[1].t}: ${text[1].v}</text>
      <text x="50" y="250" fill="#ffffff" font-family="Arial" font-size="28">${text[2].t}: ${text[2].v}</text>
      <text x="50" y="300" fill="#b0bec5" font-family="Arial" font-size="24">${text[3].t}: ${escapeXml(text[3].v).slice(0, 120)}</text>
      <text x="50" y="380" fill="#90caf9" font-family="Arial" font-size="32" font-weight="bold">Speed Comparison</text>
      <text x="50" y="430" fill="#ffffff" font-family="Arial" font-size="26">${compareText[0].t}: ${compareText[0].v}</text>
      <text x="50" y="470" fill="#ffffff" font-family="Arial" font-size="26">${compareText[1].t}: ${compareText[1].v}</text>
      <text x="50" y="510" fill="#ffffff" font-family="Arial" font-size="26">${compareText[2].t}: ${compareText[2].v}</text>
      <text x="50" y="${h - 60}" fill="#b0bec5" font-family="Arial" font-size="22">Generated by local service</text>
    </svg>
  `
  const img = await sharp(Buffer.from(svg)).png().toBuffer()
  await sharp(img).toFile(outPath)
}

export function buildAnimatedCompare({ analysis, compare, outPath }) {
  return new Promise(async (resolve, reject) => {
    try {
      const dur = 2
      const fps = 25
      const frames = dur * fps
      const w = 1280
      const h = 300
      const barMax = 900
      const pSound = Math.min(analysis.speed_mps / compare.sound_mps, 1)
      const pBullet = Math.min(analysis.speed_mps / compare.bullet_mps, 1)
      const pCheetah = Math.min(analysis.speed_mps / compare.cheetah_mps, 1)
      const outDir = path.dirname(outPath)
      const overlayDir = path.join(outDir, 'overlay_frames')
      if (!fs.existsSync(overlayDir)) fs.mkdirSync(overlayDir, { recursive: true })
      for (let i = 0; i < frames; i++) {
        const t = i / frames
        const wSound = Math.round(barMax * Math.min(t / 1, pSound))
        const wBullet = Math.round(barMax * Math.min(t / 1, pBullet))
        const wCheetah = Math.round(barMax * Math.min(t / 1, pCheetah))
        const svg = `
          <svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
            <rect x="0" y="0" width="${w}" height="${h}" fill="#0a0e12"/>
            <text x="40" y="40" fill="#00e676" font-family="Arial" font-size="36">Speed Comparison</text>
            <text x="40" y="110" fill="#90caf9" font-family="Arial" font-size="26">Speed of Sound</text>
            <text x="40" y="170" fill="#90caf9" font-family="Arial" font-size="26">Bullet</text>
            <text x="40" y="230" fill="#90caf9" font-family="Arial" font-size="26">Cheetah</text>
            <rect x="200" y="90" width="${wSound}" height="30" fill="#1de9b6" opacity="0.8"/>
            <rect x="200" y="150" width="${wBullet}" height="30" fill="#ff9100" opacity="0.8"/>
            <rect x="200" y="210" width="${wCheetah}" height="30" fill="#2962ff" opacity="0.8"/>
            <text x="${210 + wSound + 20}" y="115" fill="#ffffff" font-family="Arial" font-size="22">${Math.round(pSound * 100)}%</text>
            <text x="${210 + wBullet + 20}" y="175" fill="#ffffff" font-family="Arial" font-size="22">${Math.round(pBullet * 100)}%</text>
            <text x="${210 + wCheetah + 20}" y="235" fill="#ffffff" font-family="Arial" font-size="22">${Math.round(pCheetah * 100)}%</text>
          </svg>
        `
        const framePath = path.join(overlayDir, `frame-${String(i).padStart(3, '0')}.png`)
        const buf = await sharp(Buffer.from(svg)).png().toBuffer()
        await sharp(buf).toFile(framePath)
      }
      ffmpeg()
        .input(path.join(overlayDir, 'frame-%03d.png'))
        .inputOptions([`-framerate ${fps}`])
        .outputOptions(['-pix_fmt yuv420p', '-r 25'])
        .on('end', resolve)
        .on('error', reject)
        .save(outPath)
    } catch (e) {
      reject(e)
    }
  })
}

export function mergeIntroAndOverlay({ inputVideo, introImage, overlayVideo, outPath }) {
  return new Promise((resolve, reject) => {
    const introDur = 3
    const intro = `loopedIntro.mp4`
    const dir = path.dirname(outPath)
    const introPath = path.join(dir, intro)
    const mkIntro = new Promise((res, rej) => {
      ffmpeg(introImage)
        .loop(introDur)
        .inputOptions(['-framerate 25'])
        .outputOptions(['-pix_fmt yuv420p', '-r 25', `-vf scale=1280:-2`])
        .on('end', res)
        .on('error', rej)
        .save(introPath)
    })
    mkIntro.then(() => {
      const overlaidPath = path.join(dir, 'overlaid.mp4')
      ffmpeg(inputVideo)
        .input(overlayVideo)
        .complexFilter(`[0:v]scale=1280:-2[v0];[1:v]scale=1280:-2,format=yuva420p,colorchannelmixer=aa=0.0[ov];[v0][ov]overlay=x=0:y=50:enable='between(t,0,2)'[vout]`)
        .outputOptions(['-map [vout]', '-map 0:a?', '-c:v libx264', '-c:a copy', '-pix_fmt yuv420p'])
        .on('end', () => {
          ffmpeg()
            .input(introPath)
            .input(overlaidPath)
            .on('error', reject)
            .on('end', resolve)
            .mergeToFile(outPath, dir)
        })
        .on('error', reject)
        .save(overlaidPath)
    }).catch(reject)
  })
}

function escapeXml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

